spring.application.name=hydrosys

# CONFIGURACIÃN DE LA BASE DE DATOS PARA MARIA DB

# Datasource Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/hydrosys?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ConfiguraciÃ³n de Hibernate para MariaDB
# create = crea desde cero / update = actualiza sin borrar / create-drop = crea y borra al cerrar / validate = solo valida / none = no hace nada
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=true

# Para ver consultas con parÃ¡metros en logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# JWT Configuration - IMPORTANTE: En producción usa variables de entorno!
jwt.secret=${JWT_SECRET:5whzI+3te8Ut3MVJQZ1hjfH7m0Ro+zZ1YhPQgwbvrM7w5UWhc3cG/4ve0XcW/Cfh}

# Puerto del servidor configurable
server.port=${SERVER_PORT:8080}

# ConfiguraciÃ³n para Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
